title: "0xpinonym"
description: "Malware analysis - Reverse engineering - Systems - CTF wu - CVE exploration"
url: "https://pinonym.github.io"

theme: minima

minima:
  author:
    name: pinonym
    bio: "Malware analysis · Reverse engineering · Systems"
  social_links:
    - { platform: github, user_url: "https://github.com/pinonym" }

timezone: Europe/Paris
lang: en

# Posts
paginate: 10
paginate_path: "/page:num/"

# Syntax highlighting
highlighter: rouge
markdown: kramdown

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Socials (optionnel)
github:
  username: pinonym

# Collections
permalink: /posts/:title/

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock